language: node_js
node_js:
- '16'
services:
- docker
notifications:
  email: false
  slack:
    rooms:
      secure: CbDLXF3mFq1AWJ3z8PSMo8VJN3RyQtVteEbVge7L1n8b5ge7mc1mdyW3qnFyBedIbFccfng6fg6G05rH6m4lPq/Ygs7ETWu7naiYRtNPmIb9cBlf9QUQLr1VnYigaccubB3UUmtMn9Tp8i5QX3bPWy3OTqYXw2IzS4bHwDBDwYqNUhPr1gj+uhIhyKkQRmye5I8sYmtlr/rqNBJtetZavpXWzMtdPHkpDEw8LsMVmHr/XDxYoIWrK6nrlIRS/672pEoJsPZkgVPbx6rHpTD13ujMnfUQaWyugJlrd4uf9IVZFcsZpQYJsEhojBbNZ5EuXb0V7pHbpXa/7djreLj/LsNgZWtfiqU45YWXpm16cJ3606JCZlEVl4v/X5DBDHCjdjsMuFhWNEy+7vbWQ2KhreyoSBw/CwMA5yszidVo4wqVOJ8M9B26qb6XO5CxtLpnA7Ih9j00+uNAh0qgHXUuyC3ZaLSJlwY+CW4JEBf7leMMc7wpD7RLf0Bot+8BgtJf+fmPVLm2rVn1dcap/CijS8STzHAgMQclNRATjR6KbIkRWQYql9NipvXdusCyMwF7WZlWjVwL8gm2dcVzx5+SNK/o3GASkwOJrwAXkwixSZN65NFwqhddnKIKi7hQkVVfNwDlaLT+wZB44EHdxhBft5ktMzMz+VrOJzH39wIka3s=
    on_success: always
    on_failure: always
before_script:
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
script:
- |
  IMAGE_NAME="$TRAVIS_REPO_SLUG"
  if [[ -z "$TRAVIS_TAG" ]]; then
    IMAGE_TAG=latest
    KRAWLER_TAG=latest
  else
    IMAGE_TAG=$(node -p -e "require('./package.json').version")
    KRAWLER_TAG=$(node -p -e "require('./package.json').peerDependencies['@kalisio/krawler']")
  fi
  docker build --build-arg KRAWLER_TAG=$KRAWLER_TAG -f dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
deploy:
  provider: script
  script: docker push $IMAGE_NAME:$IMAGE_TAG
  on:
    all_branches: true
